// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTBiObhgMXo6bpzvGiYuJyv7YMsuxO-7w',
    appId: '1:80987837444:android:acfce2ab29964a74aad151',
    messagingSenderId: '80987837444',
    projectId: 'kisantara-28e1f',
    storageBucket: 'kisantara-28e1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC97PrhrC5Op2FzWdmGo0HcgZH0bL4_BRI',
    appId: '1:80987837444:ios:f13e8b823dbb17fbaad151',
    messagingSenderId: '80987837444',
    projectId: 'kisantara-28e1f',
    storageBucket: 'kisantara-28e1f.firebasestorage.app',
    iosBundleId: 'com.example.kisantara',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBksowBtS_zaTDjDpy3M_me_KpBLWobjNU',
    appId: '1:80987837444:web:c5e4ba8047a4303caad151',
    messagingSenderId: '80987837444',
    projectId: 'kisantara-28e1f',
    authDomain: 'kisantara-28e1f.firebaseapp.com',
    storageBucket: 'kisantara-28e1f.firebasestorage.app',
    measurementId: 'G-JQMKDFN2NC',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC97PrhrC5Op2FzWdmGo0HcgZH0bL4_BRI',
    appId: '1:80987837444:ios:f13e8b823dbb17fbaad151',
    messagingSenderId: '80987837444',
    projectId: 'kisantara-28e1f',
    storageBucket: 'kisantara-28e1f.firebasestorage.app',
    iosBundleId: 'com.example.kisantara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBksowBtS_zaTDjDpy3M_me_KpBLWobjNU',
    appId: '1:80987837444:web:625cc125c240372caad151',
    messagingSenderId: '80987837444',
    projectId: 'kisantara-28e1f',
    authDomain: 'kisantara-28e1f.firebaseapp.com',
    storageBucket: 'kisantara-28e1f.firebasestorage.app',
    measurementId: 'G-ES8DMX0T0W',
  );

}