import 'package:flutter/material.dart';

class AppLocalizations {
  // Using ValueNotifier to make it easy to listen to language changes globally
  static final ValueNotifier<String> currentLanguageNotifier =
      ValueNotifier<String>('Bahasa Indonesia');

  static String get currentLanguage => currentLanguageNotifier.value;

  static void changeLanguage(String newLang) {
    if (translations.containsKey(newLang)) {
      currentLanguageNotifier.value = newLang;
    }
  }

  static String translate(String key) {
    return translations[currentLanguage]?[key] ?? key;
  }

  static final Map<String, Map<String, String>> translations = {
    'Bahasa Indonesia': {
      'beranda': 'Beranda',
      'cari': 'Cari',
      'profil': 'Profil',
      'cerita_saya': 'Cerita Saya',
      'terbaru': 'Terbaru',
      'kategori': 'Kategori',
      'semua': 'Semua',
      'disimpan': 'Disimpan',
      'terakhir_dibaca': 'Terakhir Dibaca',
      'tulisan_saya': 'Tulisan Saya',
      'tulis_cerita': 'Tulis Cerita',
      'edit_profil': 'Edit Profil',
      'notifikasi': 'Notifikasi',
      'bahasa': 'Bahasa',
      'bantuan': 'Bantuan',
      'keluar': 'Keluar',
      'cerita_dibaca': 'Cerita Dibaca',
      'lencana': 'Lencana',
      'mulai_membaca': 'Mulai Membaca',
      'lanjutkan_membaca': 'Lanjutkan Membaca',
      'pilih_bahasa': 'Pilih Bahasa',
      'gunakan_bahasa_ini': 'Gunakan Bahasa Ini',
      'belum_ada_cerita': 'Belum ada cerita.',
      'belum_ada_cerita_disimpan': 'Belum ada cerita disimpan.',
      'belum_ada_riwayat': 'Belum ada riwayat membaca.',
      'belum_ada_tulisan': 'Anda belum menulis cerita apapun.',
      'tunggu_persetujuan': '⏳ Menunggu persetujuan admin',
      'ditolak_admin': '❌ Ditolak oleh admin',
      'hapus_cerita': 'Hapus Cerita?',
      'yakin_hapus': 'Apakah Anda yakin ingin menghapus cerita ini? Cerita yang dihapus tidak dapat dipulihkan.',
      'batal': 'Batal',
      'hapus': 'Hapus',
      'bagaimana_ceritanya': 'Bagaimana ceritanya?',
      'batal_simpan_cerita': 'Batal Simpan Cerita',
      'simpan_cerita_ini': 'Simpan Cerita Ini',
      'status_simpan_diperbarui': 'Status simpan cerita diperbarui.',
      'silakan_login_dahulu': 'Silakan login terlebih dahulu.',
      'cerita_berhasil_dihapus': 'Cerita berhasil dihapus.',
      'cari_cerita_ajaib': 'Cari cerita ajaib...',
      'misi_membaca': 'Misi Membaca',
      'selesaikan_cerita_lencana': 'Selesaikan 2 cerita lagi untuk lencana baru!',
      'sudah_keluar': 'Anda telah keluar dari aplikasi.',
      // Notifikasi screen
      'notifikasi_aktivitas': 'Aktivitas Terbaru',
      'pengaturan_notifikasi': 'Pengaturan Notifikasi',
      'belum_ada_notifikasi': 'Belum ada notifikasi.',
      'cerita_baru_section': 'Cerita Baru',
      'push_notif_cerita': 'Push Notification',
      'push_notif_cerita_sub': 'Dapatkan kabar saat ada cerita nusantara baru.',
      'email_notif_cerita': 'Email',
      'email_notif_cerita_sub': 'Ringkasan cerita baru lewat kotak masukmu.',
      'pembaruan_promo_section': 'Pembaruan & Promo',
      'pembaruan_aplikasi': 'Pembaruan Aplikasi',
      'pembaruan_aplikasi_sub': 'Info fitur baru dan perbaikan sistem.',
      'promosi_event': 'Promosi & Event',
      'promosi_event_sub': 'Info acara spesial dan penawaran menarik.',
      'keamanan_section': 'Keamanan',
      'keamanan_akun': 'Keamanan Akun',
      'keamanan_akun_sub': 'Pemberitahuan login atau perubahan sandi.',
      // Edit Profil screen
      'gagal_pilih_gambar': 'Gagal memilih gambar',
      'profil_diperbarui': 'Profil berhasil diperbarui!',
      'gagal_perbarui_profil': 'Gagal memperbarui profil',
      'nama_lengkap': 'Nama Lengkap (Nama Pena)',
      'masukkan_nama': 'Masukkan nama lengkap',
      'masukkan_email': 'Masukkan email',
      'bio': 'Bio',
      'tulis_tentang_kamu': 'Tulis sedikit tentang kamu',
      'simpan_perubahan': 'Simpan Perubahan',
      // Bahasa screen
      'bahasa_diubah': 'Bahasa berhasil diubah ke',
      'gagal_ubah_bahasa': 'Gagal mengubah bahasa',
      // Bantuan screen
      'cari_bantuan': 'Cari bantuan...',
      'pertanyaan_populer': 'Pertanyaan Populer',
      'faq_q1': 'Bagaimana cara menyimpan cerita?',
      'faq_a1': 'Ketuk ikon "Simpan" di pojok kanan atas saat membaca cerita untuk menyimpannya ke daftar pustaka kamu.',
      'faq_q2': 'Apakah aplikasi ini gratis?',
      'faq_a2': 'Ya! Kisantara berkomitmen untuk menyebarkan kekayaan budaya nusantara secara gratis untuk semua anak Indonesia.',
      'faq_q3': 'Cara mendapatkan lencana baru?',
      'faq_a3': 'Selesaikan misi membaca dan jelajahi berbagai kategori cerita untuk membuka lencana-lencana unik.',
      'faq_q4': 'Cerita saya tidak bisa dimuat?',
      'faq_a4': 'Pastikan koneksi internet kamu stabil, atau bersihkan cache aplikasi di pengaturan profil.',
      'faq_q5': 'Bagaimana cara membuat akun?',
      'faq_a5': 'Buka aplikasi, pilih "Daftar", masukkan email dan password kamu, kemudian verifikasi email kamu untuk menyelesaikan pendaftaran.',
      'faq_q6': 'Bisakah saya menulis cerita sendiri?',
      'faq_a6': 'Ya! Di menu "Tulis Cerita" kamu bisa membuat cerita baru. Cerita akan diperiksa oleh admin sebelum dipublikasikan.',
      'faq_q7': 'Apa itu lencana dan bagaimana cara mendapatkannya?',
      'faq_a7': 'Lencana adalah penghargaan digital yang kamu peroleh dengan menyelesaikan misi membaca dan mencapai target tertentu. Semakin banyak cerita yang dibaca, semakin banyak lencana yang bisa kamu kumpulkan.',
      'faq_q8': 'Apakah data saya aman?',
      'faq_a8': 'Kami menggunakan enkripsi tingkat industri untuk melindungi data pribadi kamu. Privasi dan keamanan kamu adalah prioritas utama kami.',
      'butuh_bantuan': 'Masih butuh bantuan?',
      'tim_kami_siap': 'Tim kami siap membantu masalah yang kamu hadapi.',
      'chat': 'Chat',
      // Categories
      'mitos': 'Mitos',
      'legenda': 'Legenda',
      'fabel': 'Fabel',
      'fantasi': 'Fantasi',
      // Notifications Screen & dialogs
      'tandai_dibaca': 'Tandai sudah dibaca',
      'hapus_semua': 'Hapus Semua',
      'hapus_semua_notifikasi': 'Hapus Semua Notifikasi?',
      'yakin_hapus_semua_notif': 'Semua notifikasi Anda akan dihapus secara permanen.',
      'menit_lalu': 'menit lalu',
      'jam_lalu': 'jam lalu',
      'hari_lalu': 'hari lalu',
      // Database Notifications translation
      'notif_title_approval': 'Cerita Disetujui',
      'notif_message_approval': 'Cerita "{title}" kamu telah disetujui oleh admin dan sudah dipublikasikan!',
      'notif_title_new_story_admin': 'Cerita Baru dari Admin',
      'notif_message_new_story_admin': 'Admin telah memposting cerita baru: "{title}"',
      'notif_message_new_story_admin_with_category': 'Admin telah memposting cerita baru: "{title}" dengan kategori {category}',
      'notif_title_new_story_user': 'Cerita Baru dari Pengguna',
      'notif_message_new_story_user': 'Pengguna "{author}" telah mempublikasikan cerita baru: "{title}"',
      'notif_title_pending_story': 'Cerita Perlu Persetujuan',
      'notif_message_pending_story': 'Pengguna "{author}" telah mengirimkan cerita baru: "{title}" dan menunggu persetujuan.',
      // Saving SnackBar
      'berhasil_menyimpan_cerita_notif': 'Cerita berhasil disimpan!',
      'batal_menyimpan_cerita_notif': 'Batal menyimpan cerita.',
    },
    'English': {
      'beranda': 'Home',
      'cari': 'Search',
      'profil': 'Profile',
      'cerita_saya': 'My Stories',
      'terbaru': 'Latest',
      'kategori': 'Categories',
      'semua': 'All',
      'disimpan': 'Saved',
      'terakhir_dibaca': 'Recently Read',
      'tulisan_saya': 'My Writings',
      'tulis_cerita': 'Write Story',
      'edit_profil': 'Edit Profile',
      'notifikasi': 'Notifications',
      'bahasa': 'Language',
      'bantuan': 'Help',
      'keluar': 'Logout',
      'cerita_dibaca': 'Stories Read',
      'lencana': 'Badges',
      'mulai_membaca': 'Start Reading',
      'lanjutkan_membaca': 'Continue Reading',
      'pilih_bahasa': 'Choose Language',
      'gunakan_bahasa_ini': 'Use This Language',
      'belum_ada_cerita': 'No stories yet.',
      'belum_ada_cerita_disimpan': 'No saved stories yet.',
      'belum_ada_riwayat': 'No reading history.',
      'belum_ada_tulisan': 'You haven\'t written any stories.',
      'tunggu_persetujuan': '⏳ Waiting for admin approval',
      'ditolak_admin': '❌ Rejected by admin',
      'hapus_cerita': 'Delete Story?',
      'yakin_hapus': 'Are you sure you want to delete this story? Deleted stories cannot be recovered.',
      'batal': 'Cancel',
      'hapus': 'Delete',
      'bagaimana_ceritanya': 'How is the story?',
      'batal_simpan_cerita': 'Unsave Story',
      'simpan_cerita_ini': 'Save This Story',
      'status_simpan_diperbarui': 'Story save status updated.',
      'silakan_login_dahulu': 'Please login first.',
      'cerita_berhasil_dihapus': 'Story deleted successfully.',
      'cari_cerita_ajaib': 'Search magic stories...',
      'misi_membaca': 'Reading Mission',
      'selesaikan_cerita_lencana': 'Complete 2 more stories for a new badge!',
      'sudah_keluar': 'You have been signed out.',
      // Notifikasi screen
      'notifikasi_aktivitas': 'Recent Activity',
      'pengaturan_notifikasi': 'Notification Settings',
      'belum_ada_notifikasi': 'No notifications yet.',
      'cerita_baru_section': 'New Story',
      'push_notif_cerita': 'Push Notification',
      'push_notif_cerita_sub': 'Get notified when there is a new folklore story.',
      'email_notif_cerita': 'Email',
      'email_notif_cerita_sub': 'Summary of new stories in your inbox.',
      'pembaruan_promo_section': 'Updates & Promos',
      'pembaruan_aplikasi': 'App Updates',
      'pembaruan_aplikasi_sub': 'Info on new features and system fixes.',
      'promosi_event': 'Promotions & Events',
      'promosi_event_sub': 'Info on special events and attractive offers.',
      'keamanan_section': 'Security',
      'keamanan_akun': 'Account Security',
      'keamanan_akun_sub': 'Notifications about login or password changes.',
      // Edit Profil screen
      'gagal_pilih_gambar': 'Failed to select image',
      'profil_diperbarui': 'Profile updated successfully!',
      'gagal_perbarui_profil': 'Failed to update profile',
      'nama_lengkap': 'Full Name (Pen Name)',
      'masukkan_nama': 'Enter full name',
      'masukkan_email': 'Enter email',
      'bio': 'Bio',
      'tulis_tentang_kamu': 'Write a little about yourself',
      'simpan_perubahan': 'Save Changes',
      // Bahasa screen
      'bahasa_diubah': 'Language successfully changed to',
      'gagal_ubah_bahasa': 'Failed to change language',
      // Bantuan screen
      'cari_bantuan': 'Search help...',
      'pertanyaan_populer': 'Popular Questions',
      'faq_q1': 'How to save a story?',
      'faq_a1': 'Tap the "Save" icon in the top right corner while reading a story to save it to your library.',
      'faq_q2': 'Is this app free?',
      'faq_a2': 'Yes! Kisantara is committed to spreading the cultural wealth of the archipelago for free to all Indonesian children.',
      'faq_q3': 'How to get new badges?',
      'faq_a3': 'Complete reading missions and explore various story categories to unlock unique badges.',
      'faq_q4': 'My story cannot be loaded?',
      'faq_a4': 'Make sure your internet connection is stable, or clear the app cache in profile settings.',
      'faq_q5': 'How do I create an account?',
      'faq_a5': 'Open the app, select "Sign Up", enter your email and password, then verify your email to complete registration.',
      'faq_q6': 'Can I write my own stories?',
      'faq_a6': 'Yes! In the "Write Story" menu you can create new stories. Your story will be reviewed by an admin before publication.',
      'faq_q7': 'What are badges and how do I earn them?',
      'faq_a7': 'Badges are digital rewards you earn by completing reading missions and reaching certain targets. The more stories you read, the more badges you can collect.',
      'faq_q8': 'Is my data safe?',
      'faq_a8': 'We use industry-level encryption to protect your personal data. Your privacy and security are our top priorities.',
      'butuh_bantuan': 'Still need help?',
      'tim_kami_siap': 'Our team is ready to help you with any problems you encounter.',
      'chat': 'Chat',
      // Categories
      'mitos': 'Myth',
      'legenda': 'Legend',
      'fabel': 'Fable',
      'fantasi': 'Fantasy',
      // Notifications Screen & dialogs
      'tandai_dibaca': 'Mark as read',
      'hapus_semua': 'Delete All',
      'hapus_semua_notifikasi': 'Delete All Notifications?',
      'yakin_hapus_semua_notif': 'All your notifications will be permanently deleted.',
      'menit_lalu': 'minutes ago',
      'jam_lalu': 'hours ago',
      'hari_lalu': 'days ago',
      // Database Notifications translation
      'notif_title_approval': 'Story Approved',
      'notif_message_approval': 'Your story "{title}" has been approved by the admin and is now published!',
      'notif_title_new_story_admin': 'New Story from Admin',
      'notif_message_new_story_admin': 'Admin has posted a new story: "{title}"',
      'notif_message_new_story_admin_with_category': 'Admin has posted a new story: "{title}" in category {category}',
      'notif_title_new_story_user': 'New Story from User',
      'notif_message_new_story_user': 'User "{author}" has published a new story: "{title}"',
      'notif_title_pending_story': 'Story Needs Approval',
      'notif_message_pending_story': 'User "{author}" has submitted a new story: "{title}" and is waiting for approval.',
      // Saving SnackBar
      'berhasil_menyimpan_cerita_notif': 'Story saved successfully!',
      'batal_menyimpan_cerita_notif': 'Story unsaved.',
    },
    'Jawa': {
      'beranda': 'Omah',
      'cari': 'Golek',
      'profil': 'Profil',
      'cerita_saya': 'Ceritaku',
      'terbaru': 'Paling Anyar',
      'kategori': 'Kategori',
      'semua': 'Kabeh',
      'disimpan': 'Disimpen',
      'terakhir_dibaca': 'Pungkasan Diwaca',
      'tulisan_saya': 'Tulisanku',
      'tulis_cerita': 'Nulis Cerita',
      'edit_profil': 'Ngowahi Profil',
      'notifikasi': 'Wara-wara',
      'bahasa': 'Basa',
      'bantuan': 'Pitulungan',
      'keluar': 'Metu',
      'cerita_dibaca': 'Cerita Diwaca',
      'lencana': 'Lencana',
      'mulai_membaca': 'Mulai Maca',
      'lanjutkan_membaca': 'Terusna Maca',
      'pilih_bahasa': 'Pilih Basa',
      'gunakan_bahasa_ini': 'Gunakake Basa Iki',
      'belum_ada_cerita': 'Durung ana cerita.',
      'belum_ada_cerita_disimpan': 'Durung ana cerita disimpen.',
      'belum_ada_riwayat': 'Durung ana riwayat wacan.',
      'belum_ada_tulisan': 'Sampeyan durung nulis cerita apa-apa.',
      'tunggu_persetujuan': '⏳ Ngenteni persetujuan admin',
      'ditolak_admin': '❌ Ditolak dening admin',
      'hapus_cerita': 'Busak Cerita?',
      'yakin_hapus': 'Apa sampeyan yakin arep mbusak cerita iki? Cerita sing dibusak ora bisa dibalekake.',
      'batal': 'Batal',
      'hapus': 'Busak',
      'bagaimana_ceritanya': 'Kepiye ceritane?',
      'batal_simpan_cerita': 'Batal Simpen Cerita',
      'simpan_cerita_ini': 'Simpen Cerita Iki',
      'status_simpan_diperbarui': 'Status simpen cerita dianyari.',
      'silakan_login_dahulu': 'Mangga mlebu dhisik.',
      'cerita_berhasil_dihapus': 'Cerita kasil dibusak.',
      'cari_cerita_ajaib': 'Golek cerita ajaib...',
      'misi_membaca': 'Misi Maca',
      'selesaikan_cerita_lencana': 'Rampungake 2 cerita maneh kanggo lencana anyar!',
      'sudah_keluar': 'Sampeyan wis metu saka aplikasi.',
      // Notifikasi screen
      'notifikasi_aktivitas': 'Aktivitas Pungkasan',
      'pengaturan_notifikasi': 'Setelan Wara-wara',
      'belum_ada_notifikasi': 'Durung ana wara-wara.',
      'cerita_baru_section': 'Cerita Anyar',
      'push_notif_cerita': 'Push Notification',
      'push_notif_cerita_sub': 'Entuk kabar nalika ana cerita nusantara anyar.',
      'email_notif_cerita': 'Email',
      'email_notif_cerita_sub': 'Ringkesan cerita anyar liwat kothak mlebu sampeyan.',
      'pembaruan_promo_section': 'Pembaruan & Promo',
      'pembaruan_aplikasi': 'Pembaruan Aplikasi',
      'pembaruan_aplikasi_sub': 'Info fitur anyar lan ndandani sistem.',
      'promosi_event': 'Promosi & Event',
      'promosi_event_sub': 'Info acara khusus lan penawaran menarik.',
      'keamanan_section': 'Keamanan',
      'keamanan_akun': 'Keamanan Akun',
      'keamanan_akun_sub': 'Wara-wara login utawa owah-owahan sandi.',
      // Edit Profil screen
      'gagal_pilih_gambar': 'Gagal milih gambar',
      'profil_diperbarui': 'Profil kasil dianyari!',
      'gagal_perbarui_profil': 'Gagal nganyari profil',
      'nama_lengkap': 'Jeneng Lengkap (Jeneng Pena)',
      'masukkan_nama': 'Lebokake jeneng lengkap',
      'masukkan_email': 'Lebokake email',
      'bio': 'Bio',
      'tulis_tentang_kamu': 'Tulis sithik babagan sampeyan',
      'simpan_perubahan': 'Simpen Owahan',
      // Bahasa screen
      'bahasa_diubah': 'Basa kasil diowahi dadi',
      'gagal_ubah_bahasa': 'Gagal ngowahi basa',
      // Bantuan screen
      'cari_bantuan': 'Golek pitulungan...',
      'pertanyaan_populer': 'Pitakon Populer',
      'faq_q1': 'Kepiye carane nyimpen cerita?',
      'faq_a1': 'Tutul lambang "Simpen" ing pojok tengen ndhuwur nalika maca cerita kanggo nyimpen ing perpustakaan sampeyan.',
      'faq_q2': 'Apa aplikasi iki gratis?',
      'faq_a2': 'Iyo! Kisantara nduweni komitmen kanggo nyebarake kasugihan budaya nusantara kanthi gratis kanggo kabeh anak Indonesia.',
      'faq_q3': 'Carane entuk lencana anyar?',
      'faq_a3': 'Rampungake misi maca lan jelajahi macem-macem kategori cerita kanggo mbukak lencana sing unik.',
      'faq_q4': 'Ceritaku ora bisa dimuat?',
      'faq_a4': 'Priksa manawa sambungan internet sampeyan stabil, utawa resiki cache aplikasi in setelan profil.',
      'faq_q5': 'Kepiye carane nggawe akun?',
      'faq_a5': 'Bukak aplikasi, pilih "Daftar", lebokake email lan sandi sampeyan, banjur veripikasi email sampeyan kanggo ngrampungake pendaftaran.',
      'faq_q6': 'Bisa apa aku nulis cerita dewe?',
      'faq_a6': 'Iyo! In menu "Nulis Cerita" kowe bisa nggawe cerita anyar. Cerita bakal diperiksa dening admin sadurunge dipublikasekake.',
      'faq_q7': 'Apa kuwi lencana lan kepiye carane entuk?',
      'faq_a7': 'Lencana yaiku panghargaan digital sing entuk kanthi ngrampungake misi maca lan mencapai target tartamtu. Manut akeh cerita sing diwaca, manut akeh lencana sing bisa dikumpulake.',
      'faq_q8': 'Apa data aku aman?',
      'faq_a8': 'Kita nggunakake enkripsi tingkat industri kanggo nglindhungi data pribadi sampeyan. Privasine lan keamanan sampeyan dadi prioritas utama kita.',
      'butuh_bantuan': 'Isih butuh pitulungan?',
      'tim_kami_siap': 'Tim kita siyap nulungi masalah sing diadhepi.',
      'chat': 'Obrolan',
      // Categories
      'mitos': 'Mitos',
      'legenda': 'Legenda',
      'fabel': 'Fabel',
      'fantasi': 'Fantasi',
      // Notifications Screen & dialogs
      'tandai_dibaca': 'Tandai wis diwaca',
      'hapus_semua': 'Busak Kabeh',
      'hapus_semua_notifikasi': 'Busak Kabeh Wara-wara?',
      'yakin_hapus_semua_notif': 'Kabeh wara-wara sampeyan bakal dibusak permanen.',
      'menit_lalu': 'menit kepungkur',
      'jam_lalu': 'jam kepungkur',
      'hari_lalu': 'dina kepungkur',
      // Database Notifications translation
      'notif_title_approval': 'Cerita Disetujoni',
      'notif_message_approval': 'Cerita "{title}" sampeyan wis disetujoni dening admin lan wis dipublikasikake!',
      'notif_title_new_story_admin': 'Cerita Anyar saka Admin',
      'notif_message_new_story_admin': 'Admin wis ngirim cerita anyar: "{title}"',
      'notif_message_new_story_admin_with_category': 'Admin wis ngirim cerita anyar: "{title}" kanthi kategori {category}',
      'notif_title_new_story_user': 'Cerita Anyar saka Pangguna',
      'notif_message_new_story_user': 'Pangguna "{author}" wis publikasikake cerita anyar: "{title}"',
      'notif_title_pending_story': 'Cerita Butuh Persetujuan',
      'notif_message_pending_story': 'Pangguna "{author}" wis ngirim cerita anyar: "{title}" lan ngenteni persetujuan.',
      // Saving SnackBar
      'berhasil_menyimpan_cerita_notif': 'Cerita kasil disimpen!',
      'batal_menyimpan_cerita_notif': 'Batal nyimpen cerita.',
    },
    'Sunda': {
      'beranda': 'Bumi',
      'cari': 'Pilari',
      'profil': 'Profil',
      'cerita_saya': 'Carita Abdi',
      'terbaru': 'Panganyarna',
      'kategori': 'Kategori',
      'semua': 'Sadayana',
      'disimpan': 'Disimpen',
      'terakhir_dibaca': 'Béh dieu Dibaca',
      'tulisan_saya': 'Tulisan Abdi',
      'tulis_cerita': 'Nulis Carita',
      'edit_profil': 'Édit Profil',
      'notifikasi': 'Bewara',
      'bahasa': 'Basa',
      'bantuan': 'Pitulung',
      'keluar': 'Kaluar',
      'cerita_dibaca': 'Carita Dibaca',
      'lencana': 'Lencana',
      'mulai_membaca': 'Mawitan Maca',
      'lanjutkan_membaca': 'Lajeungkeun Maca',
      'pilih_bahasa': 'Pilih Basa',
      'gunakan_bahasa_ini': 'Anggo Basa Ieu',
      'belum_ada_cerita': 'Teu acan aya carita.',
      'belum_ada_cerita_disimpan': 'Teu acan aya carita disimpen.',
      'belum_ada_riwayat': 'Teu acan aya riwayat bacaan.',
      'belum_ada_tulisan': 'Anjeun teu acan nulis carita nanaon.',
      'tunggu_persetujuan': '⏳ Ngantosan persetujuan admin',
      'ditolak_admin': '❌ Ditolak ku admin',
      'hapus_cerita': 'Hapus Carita?',
      'yakin_hapus': 'Naha anjeun leres hoyong ngahapus carita ieu? Carita anu dihapus moal tiasa dipulangkeun.',
      'batal': 'Batal',
      'hapus': 'Hapus',
      'bagaimana_ceritanya': 'Kumaha caritana?',
      'batal_simpan_cerita': 'Batal Simpen Carita',
      'simpan_cerita_ini': 'Simpen Carita Ieu',
      'status_simpan_diperbarui': 'Status simpen carita diropéa.',
      'silakan_login_dahulu': 'Mangga lebet heula.',
      'cerita_berhasil_dihapus': 'Carita parantos dihapus.',
      'cari_cerita_ajaib': 'Pilari carita ajaib...',
      'misi_membaca': 'Misi Maca',
      'selesaikan_cerita_lencana': 'Ngarengsekeun 2 carita deui pikeun lencana anyar!',
      'sudah_keluar': 'Anjeun parantos kaluar tina aplikasi.',
      // Notifikasi screen
      'notifikasi_aktivitas': 'Aktivitas Panganyarna',
      'pengaturan_notifikasi': 'Setélan Bewara',
      'belum_ada_notifikasi': 'Teu acan aya bewara.',
      'cerita_baru_section': 'Carita Anyar',
      'push_notif_cerita': 'Push Notification',
      'push_notif_cerita_sub': 'Kengingkeun wartos nalika aya carita nusantara enggal.',
      'email_notif_cerita': 'Email',
      'email_notif_cerita_sub': 'Ringkesan carita anyar liwat koropak anjeun.',
      'pembaruan_promo_section': 'Panganyarna & Promo',
      'pembaruan_aplikasi': 'Panganyarna Aplikasi',
      'pembaruan_aplikasi_sub': 'Info fitur anyar sareng kaleresan sistem.',
      'promosi_event': 'Promosi & Acara',
      'promosi_event_sub': 'Info acara husus sareng penawaran narik.',
      'keamanan_section': 'Kaamanan',
      'keamanan_akun': 'Kaamanan Akun',
      'keamanan_akun_sub': 'Bewara lebet atanapi parobihan kecap aksés.',
      // Edit Profil screen
      'gagal_pilih_gambar': 'Gagal milih gambar',
      'profil_diperbarui': 'Profil parantos diropéa!',
      'gagal_perbarui_profil': 'Gagal ngamutahirkeun profil',
      'nama_lengkap': 'Nami Lengkap (Nami Pena)',
      'masukkan_nama': 'Lebetkeun nami lengkep',
      'masukkan_email': 'Lebetkeun email',
      'bio': 'Bio',
      'tulis_tentang_kamu': 'Serat sakedik ngeunaan anjeun',
      'simpan_perubahan': 'Simpen Parobihan',
      // Bahasa screen
      'bahasa_diubah': 'Basa parantos dirobih janten',
      'gagal_ubah_bahasa': 'Gagal ngarobah basa',
      // Bantuan screen
      'cari_bantuan': 'Pilari pitulung...',
      'pertanyaan_populer': 'Patarosan Populér',
      'faq_q1': 'Kumaha cara nyimpen carita?',
      'faq_a1': 'Ketok ikon "Simpen" di pojok katuhu luhur nalika maca carita pikeun nyimpen kana daptar pustaka anjeun.',
      'faq_q2': 'Naha aplikasi ieu gratis?',
      'faq_a2': 'Muhun! Kisantara komitmen pikeun nyebarkeun kabeungharan budaya nusantara sacara gratis ka sadaya murangkalih Indonesia.',
      'faq_q3': 'Kumaha cara kéngingkeun lencana énggal?',
      'faq_a3': 'Rengsekeun misi maca sareng jelajah sababaraha kategori carita pikeun muka lencana anu unik.',
      'faq_q4': 'Carita abdi teu tiasa dimuat?',
      'faq_a4': 'Pastikeun sambungan internét anjeun stabil, atanapi bersihkeun cache aplikasi dina setélan profil.',
      'faq_q5': 'Kumaha cara ngadamel rekening?',
      'faq_a5': 'Bukak aplikasi, pilih "Daptar", lebetkeun email jeung kecap aksés anjeun, tuluy verifikasi email anjeun pikeun nyelesékeun pendaftaran.',
      'faq_q6': 'Bisa kami nulis carita sorangan?',
      'faq_a6': 'Muhun! Di menu "Nulis Carita" anjeun tiasa nyiptakeun carita énggal. Carita bakal diperiksa ku admin sateuacan dipublikasian.',
      'faq_q7': 'Naha éta lencana sarta kumaha cara kéngingkeun?',
      'faq_a7': 'Lencana mangrupakeun ganjaran digital anu anjeun peroleh ku ngarengsekeun misi maca jeung tungtung target tinangtu. Beuki loba carita anu dibaca, beuki loba lencana anu bisa dikumpulkeun.',
      'faq_q8': 'Naha data abdi aman?',
      'faq_a8': 'Kami nganggo enkripsi tingkat industri pikeun ngalindungan data pribadi anjeun. Privasi sarta kaamanan anjeun mangrupakeun prioritas utama kami.',
      'butuh_bantuan': 'Masih peryogi pitulung?',
      'tim_kami_siap': 'Tim kami siap ngabantosan masalah anu anjeun mayunan.',
      'chat': 'Obrolan',
      // Categories
      'mitos': 'Mitos',
      'legenda': 'Legenda',
      'fabel': 'Fabel',
      'fantasi': 'Fantasi',
      // Notifications Screen & dialogs
      'tandai_dibaca': 'Tandaan parantos dibaca',
      'hapus_semua': 'Hapus Sadaya',
      'hapus_semua_notifikasi': 'Hapus Sadaya Bewara?',
      'yakin_hapus_semua_notif': 'Sadaya bewara anjeun bakal dihapus sacara permanen.',
      'menit_lalu': 'menit ka tukang',
      'jam_lalu': 'jam ka tukang',
      'hari_lalu': 'dinten ka tukang',
      // Database Notifications translation
      'notif_title_approval': 'Carita Disatujuan',
      'notif_message_approval': 'Carita "{title}" anjeun parantos disatujuan ku admin sareng parantos dipublikasikeun!',
      'notif_title_new_story_admin': 'Carita Anyar ti Admin',
      'notif_message_new_story_admin': 'Admin parantos masangkeun carita enggal: "{title}"',
      'notif_message_new_story_admin_with_category': 'Admin parantos masangkeun carita enggal: "{title}" kalayan kategori {category}',
      'notif_title_new_story_user': 'Carita Anyar ti Pangguna',
      'notif_message_new_story_user': 'Pangguna "{author}" parantos publikasikeun carita enggal: "{title}"',
      'notif_title_pending_story': 'Carita Peryogi Persetujuan',
      'notif_message_pending_story': 'Pangguna "{author}" parantos ngirimkeun carita enggal: "{title}" sareng ngantosan persetujuan.',
      // Saving SnackBar
      'berhasil_menyimpan_cerita_notif': 'Carita parantos disimpen!',
      'batal_menyimpan_cerita_notif': 'Batal nyimpen carita.',
    },
  };
}
